services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true    # 파일 변경 감지를 위한 설정 추가
      - WATCHPACK_POLLING=true 
    dns:
      - 8.8.8.8

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/myapp
    dns:
      - 8.8.8.8

  techend:
    container_name: techend
    build:
      context: ./techend
      dockerfile: Dockerfile
    volumes:
      - ./techend:/app
    ports:
      - "2000:2000"
    stdin_open: true
    tty: true

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
